apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-portal-api-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://gitlab.com/skcloud2007/floci-gitops-secure-platform.git'
    targetRevision: main
    path: helm/customer-portal-api
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: customer-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
